source: "E:\\c++\\oloprox\\build"
destination: "C:\\Program Files\\oloprox"

copy_to:
  - from: "bin"
    to: ""
  - from: "assets"
    to: "assets"
  - from: "shaders"
    to: "assets\\shaders"

ignore: [ ".pbd" ]
