// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.engine.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_config_2eengine_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_config_2eengine_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_config_2eengine_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_config_2eengine_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_config_2eengine_2eproto;
namespace app {
namespace config {
namespace engine {
class EngineConfig;
struct EngineConfigDefaultTypeInternal;
extern EngineConfigDefaultTypeInternal _EngineConfig_default_instance_;
}  // namespace engine
}  // namespace config
}  // namespace app
PROTOBUF_NAMESPACE_OPEN
template<> ::app::config::engine::EngineConfig* Arena::CreateMaybeMessage<::app::config::engine::EngineConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace app {
namespace config {
namespace engine {

enum EWindowMode : int {
  kWindowed = 0,
  kBorderless = 1,
  kFullscreen = 2,
  EWindowMode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EWindowMode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EWindowMode_IsValid(int value);
constexpr EWindowMode EWindowMode_MIN = kWindowed;
constexpr EWindowMode EWindowMode_MAX = kFullscreen;
constexpr int EWindowMode_ARRAYSIZE = EWindowMode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EWindowMode_descriptor();
template<typename T>
inline const std::string& EWindowMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EWindowMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EWindowMode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EWindowMode_descriptor(), enum_t_value);
}
inline bool EWindowMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EWindowMode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EWindowMode>(
    EWindowMode_descriptor(), name, value);
}
// ===================================================================

class EngineConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:app.config.engine.EngineConfig) */ {
 public:
  inline EngineConfig() : EngineConfig(nullptr) {}
  ~EngineConfig() override;
  explicit PROTOBUF_CONSTEXPR EngineConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EngineConfig(const EngineConfig& from);
  EngineConfig(EngineConfig&& from) noexcept
    : EngineConfig() {
    *this = ::std::move(from);
  }

  inline EngineConfig& operator=(const EngineConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline EngineConfig& operator=(EngineConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EngineConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const EngineConfig* internal_default_instance() {
    return reinterpret_cast<const EngineConfig*>(
               &_EngineConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EngineConfig& a, EngineConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(EngineConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EngineConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EngineConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EngineConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EngineConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EngineConfig& from) {
    EngineConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EngineConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "app.config.engine.EngineConfig";
  }
  protected:
  explicit EngineConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionFieldNumber = 1,
    kWindowModeFieldNumber = 2,
  };
  // uint32 version = 1;
  void clear_version();
  uint32_t version() const;
  void set_version(uint32_t value);
  private:
  uint32_t _internal_version() const;
  void _internal_set_version(uint32_t value);
  public:

  // .app.config.engine.EWindowMode window_mode = 2;
  void clear_window_mode();
  ::app::config::engine::EWindowMode window_mode() const;
  void set_window_mode(::app::config::engine::EWindowMode value);
  private:
  ::app::config::engine::EWindowMode _internal_window_mode() const;
  void _internal_set_window_mode(::app::config::engine::EWindowMode value);
  public:

  // @@protoc_insertion_point(class_scope:app.config.engine.EngineConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t version_;
    int window_mode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_2eengine_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EngineConfig

// uint32 version = 1;
inline void EngineConfig::clear_version() {
  _impl_.version_ = 0u;
}
inline uint32_t EngineConfig::_internal_version() const {
  return _impl_.version_;
}
inline uint32_t EngineConfig::version() const {
  // @@protoc_insertion_point(field_get:app.config.engine.EngineConfig.version)
  return _internal_version();
}
inline void EngineConfig::_internal_set_version(uint32_t value) {
  
  _impl_.version_ = value;
}
inline void EngineConfig::set_version(uint32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:app.config.engine.EngineConfig.version)
}

// .app.config.engine.EWindowMode window_mode = 2;
inline void EngineConfig::clear_window_mode() {
  _impl_.window_mode_ = 0;
}
inline ::app::config::engine::EWindowMode EngineConfig::_internal_window_mode() const {
  return static_cast< ::app::config::engine::EWindowMode >(_impl_.window_mode_);
}
inline ::app::config::engine::EWindowMode EngineConfig::window_mode() const {
  // @@protoc_insertion_point(field_get:app.config.engine.EngineConfig.window_mode)
  return _internal_window_mode();
}
inline void EngineConfig::_internal_set_window_mode(::app::config::engine::EWindowMode value) {
  
  _impl_.window_mode_ = value;
}
inline void EngineConfig::set_window_mode(::app::config::engine::EWindowMode value) {
  _internal_set_window_mode(value);
  // @@protoc_insertion_point(field_set:app.config.engine.EngineConfig.window_mode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace engine
}  // namespace config
}  // namespace app

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::app::config::engine::EWindowMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::app::config::engine::EWindowMode>() {
  return ::app::config::engine::EWindowMode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_config_2eengine_2eproto
